machine:
  timezone: Europe/London
  java:
    version: oraclejdk8
  environment:
    ANDROID_HOME: /usr/local/android-sdk-linux

general:
    artifacts:
        - /home/ubuntu/AndroidCI/app/build/outputs/apk/

dependencies:
  pre:
    # Android SDK Platform 26
    - sdkmanager "build-tools;27.0.1" "platforms;android-27”
    - yes | sdkmanager --licenses
    

  cache_directories:
    - /usr/local/android-sdk-linux/platforms/android-27
    - /usr/local/android-sdk-linux/build-tools/27.0.0
    - /usr/local/android-sdk-linux/extras/android/m2repository


test:
    override:
        - ./gradlew assemble
        - cp -r app/build/outputs $CIRCLE_ARTIFACTS
