machine:
  timezone: Europe/London
  java:
    version: oraclejdk8
  environment:
    ANDROID_HOME: /usr/local/android-sdk-linux

general:
    artifacts:
        - /home/ubuntu/AndroidCI/app/build/outputs/apk/

dependencies:
    pre:
        - echo y | android update sdk --no-ui --all --filter tools,platform-tools,extra-google-m2repository,extra-google-google_play_services,extra-android-support,android-23
        - echo y | android update sdk --no-ui --all --filter build-tools-26.0.2
    cache_directories:
        - /usr/local/android-sdk-linux/tools
        - /usr/local/android-sdk-linux/build-tools/26.0.2

test:
    override:
        - ./gradlew assemble
        - cp -r app/build/outputs $CIRCLE_ARTIFACTS
