version: 2
jobs:
  build:
    docker:
      - image: bitriseio/docker-android
    working_directory: ~/OceanLife
    steps:
      - checkout
      - run:
          name: Assemble & Test (Amazon Flavour)
          command: ./gradlew assembleWithAmazon testWithAmazonDebugUnitTest
          environment:
            TERM: dumb
      - run:
          name: Assemble & Test (Google Flavour)
          command: ./gradlew assembleWithGoogle testWithGoogleDebugUnitTest
          environment:
            TERM: dumb
