version: 2
jobs:
  build:
    docker:
      - image: moisesgsaa/android-circleci 
    working_directory: ~/tmp
    steps:
      - checkout
      - run:
          name: Assemble & Test (Amazon Flavour)
          command: ./gradlew assembleWithAmazon testWithAmazonDebugUnitTest
          environment:
            TERM: dumb
      - run:
          name: Assemble & Test (Google Flavour)
          command: ./gradlew assembleDebug testDebug lint
          environment:
            TERM: dumb
